version: '3.7'

services:
  backend:
    container_name: backend
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./backend:/app/backend
    ports:
      - 8001:8000
    depends_on:
      - db
    networks:
      - local-network

  frontend:
    container_name: frontend
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3001:8080
    depends_on:
      - backend
    networks:
      - local-network

  db:
    image: mariadb:10.6.3
    restart: always
    container_name: db
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3366:3306
    networks:
      - local-network

networks:
  local-network:
    driver: bridge